# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cex < Formula
  desc "Simple CLI tool to convert currencies"
  homepage "https://github.com/janbenisek/currency-exchange"
  version "1.6.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/janbenisek/currency-exchange/releases/download/v1.6.0/cex-darwin-amd64"
      sha256 "94778bcae3590fa1b85a6b57775b360f98fa4a6660032b1b96d35f7ba904bb0f"

      def install
        bin.install "cex-darwin-arm64" => "cex" if Hardware::CPU.arm?
        bin.install "cex-darwin-amd64" => "cex" if Hardware::CPU.intel?
        bin.install "cex-linux-amd64" => "cex" if OS.linux?
      end
    end
    on_arm do
      url "https://github.com/janbenisek/currency-exchange/releases/download/v1.6.0/cex-darwin-arm64"
      sha256 "b19a2db714d4c423f96aa8015c855e21502af8e11cefa2affbe31d50d304e8bc"

      def install
        bin.install "cex-darwin-arm64" => "cex" if Hardware::CPU.arm?
        bin.install "cex-darwin-amd64" => "cex" if Hardware::CPU.intel?
        bin.install "cex-linux-amd64" => "cex" if OS.linux?
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/janbenisek/currency-exchange/releases/download/v1.6.0/cex-linux-amd64"
        sha256 "b298ce987abe892bd7719ceaa69e87af3023dea6e624800cdce5715f975ffd8b"

        def install
          bin.install "cex-darwin-arm64" => "cex" if Hardware::CPU.arm?
          bin.install "cex-darwin-amd64" => "cex" if Hardware::CPU.intel?
          bin.install "cex-linux-amd64" => "cex" if OS.linux?
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/janbenisek/currency-exchange/releases/download/v1.6.0/cex-linux-arm64"
        sha256 "2e9e3f2486475408c8179a989cb0942cac7a1e87e6baefd8036bc9f4699f720d"

        def install
          bin.install "cex-darwin-arm64" => "cex" if Hardware::CPU.arm?
          bin.install "cex-darwin-amd64" => "cex" if Hardware::CPU.intel?
          bin.install "cex-linux-amd64" => "cex" if OS.linux?
        end
      end
    end
  end

  test do
    system bin/"cex", "1", "usd", "to", "eur"
  end
end
