# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cex < Formula
  desc "Simple CLI tool to convert currencies"
  homepage "https://github.com/janbenisek/currency-exchange"
  version "1.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/janbenisek/currency-exchange/releases/download/v1.4.0/cex-darwin-amd64"
      sha256 "7f4e2f7d9896e64292d92778f1b5a46c216d03adf38d4cc650efd65ddf1160db"

      def install
        bin.install "cex-darwin-arm64" => "cex" if Hardware::CPU.arm?
        bin.install "cex-darwin-amd64" => "cex" if Hardware::CPU.intel?
        bin.install "cex-linux-amd64" => "cex" if OS.linux?
      end
    end
    on_arm do
      url "https://github.com/janbenisek/currency-exchange/releases/download/v1.4.0/cex-darwin-arm64"
      sha256 "2c39394d9cac4399880428eaae9919c596f28ee3d134ce36b4421ab2690d45a2"

      def install
        bin.install "cex-darwin-arm64" => "cex" if Hardware::CPU.arm?
        bin.install "cex-darwin-amd64" => "cex" if Hardware::CPU.intel?
        bin.install "cex-linux-amd64" => "cex" if OS.linux?
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/janbenisek/currency-exchange/releases/download/v1.4.0/cex-linux-amd64"
        sha256 "67785bb35ead572ebb565d60ab6ac34b120b7916c6ea75162ed8ce569034e66e"

        def install
          bin.install "cex-darwin-arm64" => "cex" if Hardware::CPU.arm?
          bin.install "cex-darwin-amd64" => "cex" if Hardware::CPU.intel?
          bin.install "cex-linux-amd64" => "cex" if OS.linux?
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/janbenisek/currency-exchange/releases/download/v1.4.0/cex-linux-arm64"
        sha256 "5b04f51be4302665095d326535c1f75cad68fcd066ad460d656d73754cae6e1b"

        def install
          bin.install "cex-darwin-arm64" => "cex" if Hardware::CPU.arm?
          bin.install "cex-darwin-amd64" => "cex" if Hardware::CPU.intel?
          bin.install "cex-linux-amd64" => "cex" if OS.linux?
        end
      end
    end
  end

  test do
    system bin/"cex", "1", "usd", "to", "eur"
  end
end
